CREATE TABLE `yii2_ho_feedback` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `json_objects` json DEFAULT NULL,
  `elaborated` tinyint(3) NOT NULL DEFAULT '0',
  `manual_elaboration` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `created_by` (`created_by`),
  KEY `updated_by` (`updated_by`),
  CONSTRAINT `yii2_ho_feedback_fk1` FOREIGN KEY (`created_by`) REFERENCES `yii2_user` (`id`),
  CONSTRAINT `yii2_ho_feedback_fk2` FOREIGN KEY (`updated_by`) REFERENCES `yii2_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `yii2_ho_feedback_player` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `playerID` int(11) NOT NULL DEFAULT '0',
  `experience` double NOT NULL DEFAULT '0',
  `form` double NOT NULL DEFAULT '0',
  `stamina` double NOT NULL DEFAULT '0',
  `keeper` double NOT NULL DEFAULT '0',
  `playmaking` double NOT NULL DEFAULT '0',
  `passing` double NOT NULL DEFAULT '0',
  `winger` double NOT NULL DEFAULT '0',
  `defending` double NOT NULL DEFAULT '0',
  `scoring` double NOT NULL DEFAULT '0',
  `set_pieces` double NOT NULL DEFAULT '0',
  `loyalty` double NOT NULL DEFAULT '0',
  `mother_club` tinyint(3) NOT NULL DEFAULT '0',
  `id_ho_feedback` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `created_by` (`created_by`),
  KEY `updated_by` (`updated_by`),
  KEY `id_ho_feedback` (`id_ho_feedback`),
  CONSTRAINT `yii2_ho_feedback_player_fk1` FOREIGN KEY (`id_ho_feedback`) REFERENCES `yii2_ho_feedback` (`id`),
  CONSTRAINT `yii2_ho_feedback_player_fk2` FOREIGN KEY (`created_by`) REFERENCES `yii2_user` (`id`),
  CONSTRAINT `yii2_ho_feedback_player_fk3` FOREIGN KEY (`updated_by`) REFERENCES `yii2_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `yii2_ho_feedback_position` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `id_gk` int(11) DEFAULT NULL COMMENT '"m_iId": 100',
  `id_cd_left` int(11) DEFAULT NULL COMMENT '"m_iId": 104',
  `id_cd_central` int(11) DEFAULT NULL COMMENT '"m_iId": 103',
  `id_cd_right` int(11) DEFAULT NULL COMMENT '"m_iId": 102',
  `id_wb_left` int(11) DEFAULT NULL COMMENT '"m_iId": 105',
  `id_wb_right` int(11) DEFAULT NULL COMMENT '"m_iId": 101',
  `id_im_left` int(11) DEFAULT NULL COMMENT '"m_iId": 109',
  `id_im_central` int(11) DEFAULT NULL COMMENT '"m_iId": 108',
  `id_im_right` int(11) DEFAULT NULL COMMENT '"m_iId": 107',
  `id_w_left` int(11) DEFAULT NULL COMMENT '"m_iId": 110',
  `id_w_right` int(11) DEFAULT NULL COMMENT '"m_iId": 106',
  `id_fw_left` int(11) DEFAULT NULL COMMENT '"m_iId": 113',
  `id_fw_central` int(11) DEFAULT NULL COMMENT '"m_iId": 112',
  `id_fw_right` int(11) DEFAULT NULL COMMENT '"m_iId": 111',
  `id_ho_feedback` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ID_HO_FEEDBACK` (`id_ho_feedback`) USING BTREE,
  KEY `created_by` (`created_by`),
  KEY `updated_by` (`updated_by`),
  KEY `yii2_ho_feedback_position_fk4` (`id_gk`),
  KEY `yii2_ho_feedback_position_fk5` (`id_cd_left`),
  KEY `yii2_ho_feedback_position_fk6` (`id_cd_central`),
  KEY `yii2_ho_feedback_position_fk7` (`id_cd_right`),
  KEY `yii2_ho_feedback_position_fk8` (`id_wb_left`),
  KEY `yii2_ho_feedback_position_fk9` (`id_wb_right`),
  KEY `yii2_ho_feedback_position_fk10` (`id_im_left`),
  KEY `yii2_ho_feedback_position_fk11` (`id_im_central`),
  KEY `yii2_ho_feedback_position_fk12` (`id_im_right`),
  KEY `yii2_ho_feedback_position_fk13` (`id_w_left`),
  KEY `yii2_ho_feedback_position_fk14` (`id_w_right`),
  KEY `yii2_ho_feedback_position_fk15` (`id_fw_left`),
  KEY `yii2_ho_feedback_position_fk16` (`id_fw_central`),
  KEY `yii2_ho_feedback_position_fk17` (`id_fw_right`),
  CONSTRAINT `yii2_ho_feedback_position_fk1` FOREIGN KEY (`id_ho_feedback`) REFERENCES `yii2_ho_feedback` (`id`),
  CONSTRAINT `yii2_ho_feedback_position_fk10` FOREIGN KEY (`id_im_left`) REFERENCES `yii2_ho_feedback_player` (`id`),
  CONSTRAINT `yii2_ho_feedback_position_fk11` FOREIGN KEY (`id_im_central`) REFERENCES `yii2_ho_feedback_player` (`id`),
  CONSTRAINT `yii2_ho_feedback_position_fk12` FOREIGN KEY (`id_im_right`) REFERENCES `yii2_ho_feedback_player` (`id`),
  CONSTRAINT `yii2_ho_feedback_position_fk13` FOREIGN KEY (`id_w_left`) REFERENCES `yii2_ho_feedback_player` (`id`),
  CONSTRAINT `yii2_ho_feedback_position_fk14` FOREIGN KEY (`id_w_right`) REFERENCES `yii2_ho_feedback_player` (`id`),
  CONSTRAINT `yii2_ho_feedback_position_fk15` FOREIGN KEY (`id_fw_left`) REFERENCES `yii2_ho_feedback_player` (`id`),
  CONSTRAINT `yii2_ho_feedback_position_fk16` FOREIGN KEY (`id_fw_central`) REFERENCES `yii2_ho_feedback_player` (`id`),
  CONSTRAINT `yii2_ho_feedback_position_fk17` FOREIGN KEY (`id_fw_right`) REFERENCES `yii2_ho_feedback_player` (`id`),
  CONSTRAINT `yii2_ho_feedback_position_fk2` FOREIGN KEY (`created_by`) REFERENCES `yii2_user` (`id`),
  CONSTRAINT `yii2_ho_feedback_position_fk3` FOREIGN KEY (`updated_by`) REFERENCES `yii2_user` (`id`),
  CONSTRAINT `yii2_ho_feedback_position_fk4` FOREIGN KEY (`id_gk`) REFERENCES `yii2_ho_feedback_player` (`id`),
  CONSTRAINT `yii2_ho_feedback_position_fk5` FOREIGN KEY (`id_cd_left`) REFERENCES `yii2_ho_feedback_player` (`id`),
  CONSTRAINT `yii2_ho_feedback_position_fk6` FOREIGN KEY (`id_cd_central`) REFERENCES `yii2_ho_feedback_player` (`id`),
  CONSTRAINT `yii2_ho_feedback_position_fk7` FOREIGN KEY (`id_cd_right`) REFERENCES `yii2_ho_feedback_player` (`id`),
  CONSTRAINT `yii2_ho_feedback_position_fk8` FOREIGN KEY (`id_wb_left`) REFERENCES `yii2_ho_feedback_player` (`id`),
  CONSTRAINT `yii2_ho_feedback_position_fk9` FOREIGN KEY (`id_wb_right`) REFERENCES `yii2_ho_feedback_player` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `yii2_ho_feedback_rating` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `leftDefense` double NOT NULL DEFAULT '0',
  `centralDefense` double NOT NULL DEFAULT '0',
  `rightDefense` double NOT NULL DEFAULT '0',
  `midfield` double NOT NULL DEFAULT '0',
  `leftAttack` double NOT NULL DEFAULT '0',
  `centralAttack` double NOT NULL DEFAULT '0',
  `rightAttack` double NOT NULL DEFAULT '0',
  `id_ho_feedback` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ID_HO_FEEDBACK` (`id_ho_feedback`) USING BTREE,
  KEY `created_by` (`created_by`),
  KEY `updated_by` (`updated_by`),
  CONSTRAINT `yii2_ho_feedback_rating_fk1` FOREIGN KEY (`id_ho_feedback`) REFERENCES `yii2_ho_feedback` (`id`),
  CONSTRAINT `yii2_ho_feedback_rating_fk2` FOREIGN KEY (`created_by`) REFERENCES `yii2_user` (`id`),
  CONSTRAINT `yii2_ho_feedback_rating_fk3` FOREIGN KEY (`updated_by`) REFERENCES `yii2_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `yii2_ho_feedback_system_info` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `os` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `ho_version` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `java_version` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `ho_token` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `id_ho_feedback` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ID_HO_FEEDBACK` (`id_ho_feedback`) USING BTREE,
  KEY `created_by` (`created_by`),
  KEY `updated_by` (`updated_by`),
  CONSTRAINT `yii2_ho_feedback_system_info_fk1` FOREIGN KEY (`id_ho_feedback`) REFERENCES `yii2_ho_feedback` (`id`),
  CONSTRAINT `yii2_ho_feedback_system_info_fk2` FOREIGN KEY (`created_by`) REFERENCES `yii2_user` (`id`),
  CONSTRAINT `yii2_ho_feedback_system_info_fk3` FOREIGN KEY (`updated_by`) REFERENCES `yii2_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
